### ISSUE TITLE
From Josh/Crater

### ISSUE THREAD

**Issue by ryw** [astronomerio/meteor-astronomer#15] opened 2015-09-17 17:46 UTC
Hmm, getting this in my crater logs:
```
error caught on publication:  null :  Symbol is not defined
Exception from sub id undefined ReferenceError: Symbol is not defined
   at [object Object].Package (packages/astronomerio:core/dist/publications.js:21:1)
```

**Comment by schnie** [comment] 2015-09-21 17:07
Duplicate of #14.  Will update there when fixed (today).

**Closed by schnie** 2015-09-21 17:07 UTC
